<?php

namespace AppBundle\Repository;

/**
 * RelativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelativeRepository extends \Doctrine\ORM\EntityRepository
{
}
